name: Remove Commits from August 2024

on:
  workflow_dispatch:

jobs:
  remove_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.email "abhigowda0190@gmail.com"
          git config --global user.name "Abhishek-BG"

      - name: Identify and Remove Commits from August 2024
        run: |
          # Identify commits from August 2024
          commits_to_remove=$(git log --pretty=format:"%H" --since="2024-08-01" --until="2024-12-31" --author="abhigowda0190@gmail.com")

          # Check if there are commits to remove
          if [ -z "$commits_to_remove" ]; then
            echo "No commits found for August 2024."
            exit 0
          fi

          # Remove each commit
          for commit in $commits_to_remove; do
            git rebase --onto $(git rev-list --reverse $commit^..HEAD | head -n 1) $commit^
          done

      - name: Verify Commits
        run: git log --oneline

      - name: Push Changes
        env:
          AUTO_COMMIT: ${{ secrets.AUTO_COMMIT }}
        run: |
          git remote set-url origin https://x-access-token:${AUTO_COMMIT}@github.com/${{ github.repository }}.git
          git push origin main --force
