name: Auto commit for previous years

on:
  push:
    branches:
      - main

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.email "abhigowda0190@gmail.com"
          git config --global user.name "Abhishek-BG"

      - name: Generate Commits for Previous Years
        run: |
          # Array of commit messages
          arr=(
            "Updates"
            "New Updates"
            "Fixtures"
            "Commit"
            "Updated client folder"
            "New Commit"
            "Model"
            "Recent Updates"
            "Updated index"
            "Changes to source"
            "Refactor code"
            "Fix bugs"
            "Improve performance"
            "Update dependencies"
            "Add new feature"
            "Optimize code"
            "Code cleanup"
            "Update documentation"
            "Enhance UI"
            "Bug fixes and improvements"
            "Update README"
            "Improve UX"
            "Fix typos"
            "Update configs"
          )

          # Function to generate commits for a specific year
          generate_commits() {
            year=$1
            num_days=$2
            start_date=$(date -d "$year-01-01" '+%Y-%m-%d')
            end_date=$(date '+%Y-%m-%d')  # Current date

            all_dates=()

            # Generate all dates from the start of the year to today
            while [[ "$start_date" < "$end_date" ]]; do
              all_dates+=("$start_date")
              start_date=$(date -d "$start_date + 1 day" '+%Y-%m-%d')
            done

            # Select random days
            random_days=($(shuf -e "${all_dates[@]}" -n "$num_days"))
            
            # Make commits for each random day
            for day in "${random_days[@]}"; do
              num_commits=$((RANDOM % 17 + 1))
              for ((j = 0; j < num_commits; j++)); do
                commit_date=$(date -d "$day" '+%Y-%m-%dT%H:%M:%SZ')
                rand=$((RANDOM % ${#arr[@]}))
                commit_message="${arr[$rand]} - $commit_date"
                echo "$commit_date" > LAST_UPDATED
                if git diff --quiet; then
                  echo "No changes to commit for $commit_date"
                else
                  git add LAST_UPDATED
                  GIT_COMMITTER_DATE="$commit_date" git commit -m "$commit_message" --date="$commit_date"
                fi
              done
            done
          }

          # Generate commits for each year
          generate_commits 2024 120  # Only up to current date

      - name: Verify Commits
        run: git log --oneline

      - name: Push Changes
        env:
          AUTO_COMMIT: ${{ secrets.AUTO_COMMIT }}
        run: |
          git remote set-url origin https://x-access-token:${AUTO_COMMIT}@github.com/${{ github.repository }}.git
          git push origin main --force
