name: Remove Commits from August to December 2024

on:
  workflow_dispatch:

jobs:
  remove_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.email "abhigowda0190@gmail.com"
          git config --global user.name "Abhishek-BG"

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Remove Commits from August to December 2024
        run: |
          git filter-repo --commit-callback '
          if commit.committer_date >= "2024-08-01T00:00:00Z" and commit.committer_date <= "2024-12-31T23:59:59Z":
              commit.skip()' 

      - name: Verify Commits
        run: git log --oneline

      - name: Push Changes
        env:
          AUTO_COMMIT: ${{ secrets.AUTO_COMMIT }}
        run: |
          git remote set-url origin https://x-access-token:${AUTO_COMMIT}@github.com/${{ github.repository }}.git
          git push origin main --force
