name: Auto commit for previous year

on:
  push:
    branches:
      - main # Adjust branch name if needed

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --local user.email "abhigowda0190@gmail.com"
          git config --local user.name "Abhishek-BG"

      - name: Fetch and Rebase
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Generate Commits for the Past Year
        run: |
          arr=(
            "Updates"
            "New Updates"
            "Fixtures"
            "Commit"
            "Updated client folder"
            "New Commit"
            "Model"
            "Recent Updates"
            "Updated index"
            "Changes to source"
            "Refactor code"
            "Fix bugs"
            "Improve performance"
            "Update dependencies"
            "Add new feature"
            "Optimize code"
            "Code cleanup"
            "Update documentation"
            "Enhance UI"
            "Bug fixes and improvements"
            "Update README"
            "Improve UX"
            "Fix typos"
            "Update configs"
          )

          for i in {365..1}; do
            commit_date=$(date -d "$i days ago" '+%Y-%m-%dT%H:%M:%SZ')
            rand=$((RANDOM % ${#arr[@]}))
            commit_message="${arr[$rand]} - $commit_date"
            echo "$commit_date" > LAST_UPDATED
            git add LAST_UPDATED
            GIT_COMMITTER_DATE="$commit_date" git commit -m "$commit_message" --date="$commit_date"
          done

      - name: Verify Commits
        run: git log --oneline

      - name: Push Changes
        run: |
          git push origin main --force
