name: Remove Commits from August to December 2024

on:
  push:
    branches:
      - main

jobs:
  remove_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.email "abhigowda0190@gmail.com"
          git config --global user.name "Abhishek-BG"

      - name: Remove Commits from August to December 2024
        run: |
          # Create a backup branch
          git checkout -b backup-branch
          git push origin backup-branch

          # Remove commits from August 2nd to December 31st, 2024
          git filter-branch --commit-filter '
            if [ "$(git show -s --format=%ai $GIT_COMMIT)" \> "2024-08-02" ] && [ "$(git show -s --format=%ai $GIT_COMMIT)" \< "2025-01-01" ]; then
              skip_commit "$@";
            else
              git commit-tree "$@";
            fi' HEAD

          # Push the changes
          git push origin main --force

      - name: Verify Commits
        run: git log --oneline

      - name: Push Changes
        env:
          AUTO_COMMIT: ${{ secrets.AUTO_COMMIT }}
        run: |
          git remote set-url origin https://x-access-token:${AUTO_COMMIT}@github.com/${{ github.repository }}.git
          git push origin main --force

      - name: Cleanup Backup Branch
        run: |
          # Delete the backup branch from remote
          git push origin --delete backup-branch
